language: scala
scala:
  - 2.12.8

os:
  - osx
  - linux

osx_image: xcode9.2

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi

cache:
  directories:
  - $HOME/Library/Caches/Homebrew

addons:
  homebrew:
    packages:
    - gmp
    - re2
    - pkgconfig
    - libtool
    - protobuf
    casks:
    - osxfuse
    update: true
  apt:
    packages:
    - libre2-dev
    - python3-pip
    - makedev
    - fuse
    - libfuse-dev
    - libsqlite3-dev
    - libgmp-dev
    - libncurses5-dev
    - pkg-config
    - git
    - g++
    - gcc
    - libtool-bin

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source continuous-integration/travis/install_deps_osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source continuous-integration/travis/install_deps_linux.sh; fi

jobs:
  include:
    - stage: "Compile"
      name: "Compiling Scala for E300"
      script: wake -v compileScalaModule e300ScalaModule
    - stage: "Compile"
      name: "Compiling Scala for U500"
      script: wake -v compileScalaModule u500ScalaModule
    - stage: test
      name: "Generating Verilog for E300"
      script: wake -v makeRTL e300ArtyDUTPlan
    - stage: test
      name: "Generating Verilog for U500"
      script: wake -v makeRTL u500VC707DUTPlan
